from thingspace.exceptions.CloudError import CloudError


class OutOfSyncError(CloudError):
    pass
